# Global configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'app_metrics'
    metrics_path: '/metrics'
    static_configs:
        # app is the service name in the compose file
      - targets: ['app:8000','localhost:8000'] 
